version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "click-tracker"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-h0j3910n4rm6"
s3_prefix = "click-tracker"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
